version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: ./scraper
    depends_on:
      - mongo

  flask:
    build: ./gui
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=production

volumes:
  mongo_data:
